apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{ .Values.certManagerIssuerEmail }}"
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            name: hello-world

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-tls
spec:
  secretName: hello-world-tls
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
  commonName: myownserver.thomasbouillon.fr
  dnsNames:
    - myownserver.thomasbouillon.fr